<?php

namespace RANH\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends EntityRepository
{

    public function findByUserId($idU)
    {
        $em = $this->getEntityManager();

        $dql = "SELECT ad 
          FROM RANHUserBundle:Article art 
          JOIN RANHUserBundle:Ad ad
          WHERE ad.userId = :idU 
          AND art.id = ad.articleId";
        $query = $em->createQuery($dql);
        $query->setParameter('idU', $idU);
        $ad= $query->getResult();

        return $ad;
    }


}
