article:
    path:     /{id}
    defaults: { _controller: "RANHUserBundle:Article:index" }
    methods:  [GET]

article_show:
    path:     /{id}/show
    defaults: { _controller: "RANHUserBundle:Article:show" }

article_new:
    path:     /new
    defaults: { _controller: "RANHUserBundle:Article:new" }

article_create:
    path:     /create
    defaults: { _controller: "RANHUserBundle:Article:create" }
    methods:  POST

article_edit:
    path:     /{id}/edit
    defaults: { _controller: "RANHUserBundle:Article:edit" }

article_update:
    path:     /{id}/update
    defaults: { _controller: "RANHUserBundle:Article:update" }
    methods:  [POST, PUT]

article_delete:
    path:     /{id}/delete
    defaults: { _controller: "RANHUserBundle:Article:delete" }
    methods:  [POST, DELETE]

article_ajax:
    path: /subcategorias
    defaults: { _controller: "RANHUserBundle:Article:obtenerSubcat" }

